### ISSUE TITLE
I made a map 

### ISSUE THREAD

**Issue by D4ngerKitty** [UnsignedArduino/Racers#1]
@UnsignedArduino I made a map for your game I think you could just copy and paste it in your game racers if you want 
https://arcade.makecode.com/87294-18391-89547-32948
it should be pretty easy to add

**Comment by UnsignedArduino** [comment]
Thanks! Great map and the tiles are amazing as usual!

Also funny thing, first time I played this map:

![image](https://user-images.githubusercontent.com/38868705/190917427-a7f58080-dfe6-4968-a42a-42f30614b6da.png)
