### ISSUE TITLE
I made another map 

### ISSUE THREAD

**Issue by D4ngerKitty** [UnsignedArduino/Racers#2]
I am really enjoying making maps for this I might continue to do this once the game jam is over 
https://makecode.com/_33W1yDVDc0vV

**Comment by D4ngerKitty** [comment]
Just saw the you posted the game on the forum before I posted this 
Should have checked 
LOL

**Comment by UnsignedArduino** [comment]
Haha, it's fine I should be able to add it in before Friday, I don't think they would mind - it's just another map not like more features. Plus there were only like 3 submissions :(
